-- This file was manually edited after being generated by drizzle-kit, to include `IF NOT EXISTS` statements and the `INCLUDE` clause in the index creation.

CREATE TABLE IF NOT EXISTS "restake_transactions_grouped" (
	"staker_address" text NOT NULL,
	"sender_address" text NOT NULL,
	"time_window" timestamp (3) NOT NULL,
	"aggregated_value" bigint NOT NULL,
	CONSTRAINT "restake_transactions_grouped_pkey" PRIMARY KEY("staker_address","time_window","sender_address")
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "staker_time_idx" ON "restake_transactions_grouped" USING btree ("staker_address","time_window") INCLUDE ("aggregated_value","sender_address");