name: Check

on:
  - push

jobs:
  format-and-lint:
    name: Format and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/bun.lockb') }}
      - uses: oven-sh/setup-bun@v2

      - run: bun install
      - run: bun dprint check
      - run: bun lint
